/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SIEMMessage_CONSTANTS_H
#define SIEMMessage_CONSTANTS_H

#include "SIEMMessage_types.h"

namespace SIEM { namespace thrift {

class SIEMMessageConstants {
 public:
  SIEMMessageConstants();

};

extern const SIEMMessageConstants g_SIEMMessage_constants;

}} // namespace

#endif
