/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SIEMMessage_constants.h"

namespace SIEM { namespace thrift {

const SIEMMessageConstants g_SIEMMessage_constants;

SIEMMessageConstants::SIEMMessageConstants() {
}

}} // namespace

